### ISSUE TITLE
Make me an admin

### ISSUE THREAD

**Issue by dgkeyes** [oabby1/R-reports#1] opened 2021-06-11 13:41 UTC
Hey @oabby1 thanks for adding me. I think you need to set me as an admin on this repo so I can see how you set things up and figure out why GitHub Pages isn't working.

**Comment by oabby1** [comment] 2021-06-11 15:53
@dgkeyes I can't find how to do that. I could try transferring my repo to you? Or can you tell me how to make you an admin? Meanwhile I'll explore Netlify.

**Comment by oabby1** [comment] 2021-06-11 16:01
Ok, I did get it to work with Netlify! https://silly-hermann-8abb69.netlify.app/measles-vax-rates-in-us-schools

Still curious what might be going on with Github pages, if you have time to check, or maybe we don't need to worry about it?

**Comment by oabby1** [comment] 2021-06-11 16:41
@dgkeyes I wonder if this will help, but I get this message when I push from Studio to Github: >>> /usr/bin/git push origin HEAD:refs/heads/master
remote: This repository moved. Please use the new location:        
remote:   https://github.com/rin3-spring-2021/Rin3mo.git        
To https://github.com/oabby1/Rin3mo.git
   c2c1216..9645b2d  HEAD -> master

When I tried to view my updated html report after testing in Netlify, I can see it's not updated, and I'm worried I will have to import to my oabby1 public repo every time I want an update to come through. How do I now setup directly to push to my oabby1? @charliejhadley I wonder if I could do a quick connect with you (or @dgkeyes) to make sure I'm setting my GitHub up to my oabby1 instead of rin3mo (I see my original R script GitHub setup file, where I think I change to oabby1, but I also don't have my original code in my Rmd files to confirm I'm doing it right). 

I'll also look up the original GitHub setup recordings you sent out earlier this course.

**Comment by dgkeyes** [comment] 2021-06-11 17:24
Super, glad you got it working on Netlify! Honestly, I would just use that. GitHub Pages is really slow to update (sometimes up to 15 minutes) while Netlify is almost instantaneous. 

On the location of your repo, [I made a short video to explain what's going on and how to change it](https://share.rfor.us/JruD6v7E). Let me know if this helps!

**Comment by oabby1** [comment] 2021-06-11 17:47
David, this sort of helps, except I think the problem is that my Rin3mo repo has all the updated R studio commits, but my oabby1 doesn't (look for the file ending in '-slides.rmd' as an example; it's not in your video either.) My GitHub setup file is in my oabby1 repo if you want to take a look. Do I have to set something similar up within Rin3mo in Rstudio to tell it to push to oabby1 instead? If you pull down my Run3mo repo, maybe that will help?

I connected GitHub desktop to my oabby1, but when I open it in Rstudio the other files are missing (I find them when I open the other repo in Rstudio). Should I try to get Rin3mo to show up on my desktop GitHub as well? 

Sorry!!

**Comment by dgkeyes** [comment] 2021-06-11 18:38
Ah, I see. So, if you want to have all of your commit history, we will need to transfer ownership of the repo from rin3-spring-2021 to your personal account. I'll do that now and you should get a notification. Once you accept that, you'll need to connect that repo to Netlify following the same process you used for this repo. Let me know if you have any questions!

**Comment by dgkeyes** [comment] 2021-06-11 18:40
Actually, I had to first transfer it to my personal account, then to you. Just FYI.

**Comment by oabby1** [comment] 2021-06-11 19:18
THANK YOU!

**Closed as completed by oabby1** 2021-06-11 19:18 UTC
